### ISSUE TITLE
Help with "Add from file" feature with .obj file

### ISSUE THREAD

**Issue by horsto** [brainglobe/bg-brainrender-gui#4]
Hi, I have a question about the "Add from file" feature of the GUI. I am trying to load an .obj file export from Autodesk Fusion 360, but the model does not appear on the main canvas. 

I tried loading the model in `brainrender`, similar to how it is described in the example (https://github.com/BrancoLab/BrainRender/blob/master/Examples/user_data/add_object_to_scene.py), but had to move / scale the object significantly to somehow make it appear in the scene. 

How can I adjust parameters before exporting files (is that possible at all?) so they at least get the correct scale for importing them into a brainrender scene?

**Comment by FedeClaudi** [comment]
hey, 

one thing you can do in braindender is, when creating the `scene` to set:
```
scene = Scene(add_root=None)
```

this way the scene will be empty. You can then add your object and render, to check that it's loaded correctly. 

I suggest this because usually the problem is that meshes in `brainrender` are very large (in therms of "physical" dimensions): the units are in micrometers. That means that a point at 1mm from the origin along each `XYZ` direction will be at `[1000, 1000, 1000]`. If your object was designed using a different scale such that e.g. a point at 1mm is at `[100, 100, 100]`, the object will be 1/10th of the size you'd expect relative to the other meshes. You might have to scale your mesh accordingly. 

The other possible issues are that the object you're loading is far from the origin of the rendering. If you set `brainrender.SHOW_AXES = True` before creating your `Scene` you can see where the origin is in `brainrender`:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/17436313/90338702-61d2da00-dfe3-11ea-81eb-5e7c20fed172.png">

if your object is very far from the origin you can't see both it and the brain at the same time. You'll have to fix this by translating (and perhaps rotating) the object accordingly. 


> How can I adjust parameters before exporting files (is that possible at all?) so they at least get the correct scale for importing them into a brainrender scene?

The main thing I can think of is that there might be some setting in Fusion to specify the unit of measurement of the output .obj, but not sure: I never tried this. What kind of object are you designing? Perhaps if I know more I can give you more advice. 

----

Just thought of an alternative solution. One thing you can do is to load the `.obj` files that brainrender uses to render brain regions into Fusion. Then you can design your object around it and it **should** be fine when you export it to .obj. 
You can find where the files are saved with for instance:
```
scene.atlas.meshfile_from_structure('root')
```

hope this work, let me know!

**Comment by horsto** [comment]
Thanks a lot for the thorough reply! This was very helpful.

It is great that you can retrieve the .obj files that brainrender uses that easily and play with them. I imported the `root` (whole brain) .obj file into Fusion360 (for me it was located under `~/.brainglobe/allen_mouse_25um_v0.3/meshes/997.obj`. Then I realised that I had to scale up my model by a factor of 10,000 to make it fit (it was designed in mm) - not sure I understand what was going on there because when I exported the rescaled and repositioned object from Fusion360 as .obj file and rendered in brainrender (or the GUI), the object was suddenly 10x too big. So rescaling the object in Fusion360 by 0.1 with respect to the origin of the brain and exporting again as .obj did the trick and I can now view my model both in the GUI and in brainrender without further translation / scaling. I am not sure where the factor 10 comes from when I was just opening the `997.obj` file in Fusion360. 

Anyway, this way worked for me and because the origin is maintained when opening the brain .obj file in Fusion360, it is quite easy to align / model anything and then import it into brainrender or brainrender-gui after scaling by 0.1. This is so nice!

**Comment by FedeClaudi** [comment]
hey that's great to hear. Not sure why the factor 10 is off, I might be forgetting something. It's good that it worked out in then end!
