### ISSUE TITLE
Python 3.8 and pip

### ISSUE THREAD

**Issue by vitay** [brainglobe/bg-brainrender-gui#9]
I am unable to pip install bg-brainrender-gui using Python 3.8.5:

`  
Link requires a different Python (3.8.5 not in: '>=3.6, <3.8'): https://files.pythonhosted.org/packages/48/7d/11899e40a30b301698c5de558a78710e1de4f776cb939faa756b797f17bd/bg_brainrender_gui-0.0.5rc3-py3-none-any.whl#sha256=ee763bcfb3eef8bd34362458dae1ebf8a10306e9bb3f5180c8533dd0992f63a1 (from https://pypi.org/simple/bg-brainrender-gui/) (requires-python:>=3.6, <3.8)
Given no hashes to check 0 links for project 'bg-brainrender-gui': discarding no candidates
ERROR: Could not find a version that satisfies the requirement bg-brainrender-gui (from versions: none)
ERROR: No matching distribution found for bg-brainrender-gui
`

I guess it comes from this line in setup.py:

`
python_requires=">=3.6, <3.8",
`

**Comment by FedeClaudi** [comment]
Hi @vitay  thanks for getting in touch. 

That's correct. The current version of [brainrender](https://github.com/BrancoLab/brainrender) (which this GUI depends upon) does not work with python `>3.7.0`. That's because of some dependendencies conflicts for the packages that `allensdk` depends upon. 
However in the [next release](https://github.com/BrancoLab/brainrender/issues/104) of `brainrender` this will not be an issue and therefore `bg-brainrender-gui` will also work with more recent versions of python. 

Hope this clarifies any doubt, but let me know otherwise. 
Also, if you need to be testing this code with python 3.8.5 we can make the necessary changes to `bg-brainrender-gui` in a development branch while we await the next release of `brainrender`.

**Comment by vitay** [comment]
Thanks, I'll wait for the next brainrender release and use an older conda environment in the meantime.
